context:
  expressions:
    answerQuestion:
      - "@promptVerb (me) [an, the, the following] answer to [this, that, the,
        the following] question"
      - Answer (me) [this, the, the following, that] question
    cancel:
      - (no) wait a second
      - (no) cancel
      - (no) never mind
    focusWindow:
      - "[select, go to, focus the] window number
        $pv.SingleDigitInteger:windowNumber"
      - "[go to, focus, switch to] the [$pv.SingleDigitOrdinal:windowNumber,
        $windowName:windowName] window"
    getScript:
      - "@promptVerb (me) [a, an] ($programmingLanguage:language) script"
    openWindow:
      - "[open, launch] (a) new emacs window"
    simplyTranscribe:
      - Send (this, that, the following, what follows) to (the) keyboard
      - Write [this, that, the following, what follows]
      - Transcribe
    setVolume:
      - $volumeSetting:volumeSetting (the volume)
      - (Set) (the) [volume, sound] (to) $pv.Percent:percentage
  slots:
    programmingLanguage:
      - stump
      - lisp
      - e lisp
      - c plus plus
      - javascript
      - emacs
      - shell
      - python
    promptType:
      - question
      - script
    volumeSetting:
      - mute
      - unmute
    windowName:
      - browser
      - chrome
      - emacs
      - fire fox
      - google search
      - internet
      - kitty
      - shell
      - sound
      - sound control
      - web

  macros:
    articlesAndDemonstratives:
      - a
      - an
      - that
      - the
      - this
    generate:
      - generate
      - give
      - write
    promptVerb:
      - I need
      - I want
      - generate
      - give
      - write
